---
title: "Visualisation_DESMANVariants_Snk - Avril 2023"
output:
  pdf_document: default
  html_document: default
date: "2023-04-24"
---



```{r eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE}

#Chargement des librairies

library(ggplot2)                                                           # Packages de représentations graphiques
library(plotly)                                                            # "
library(tidyverse)                                                         # " d'organisation des données
library(reshape2)                                                          # " de manipulation et formatage des tableaux 
library(wesanderson)                                                       # " palette de couleurs
library(RColorBrewer)                                                      # " "
library(comparator)                                                        # " Compare une paire de chaînes ou de séquences en déterminant si elles sont identiques ou non.
library(rmarkdown)


# Choix du gène ici, ça le change partout dans le script.
genename="tet_44__1_NZ_ABDU01000081"

cat(paste("Gene_name",genename, sep = ": "))
```



## *Nombre de variants optimals du géne*

```{r function1,  eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy = FALSE}
 
### fonction1: calcul du nombre de variants optimals : """e,g: si nous demandons à Desman 10 variants, cette fonction permettra de voir parmi les 10 variants celui optimal (correspondant à la tangent de la courbe de déviance)"""
figure_nb_variants <- function (fichier){
  fichier_fit = read.csv(fichier, sep=',', header=FALSE)
  colnames(fichier_fit) = c( "H","G", "G2", "LP","Dev")
  return(fichier_fit)
}

### Courbe de déviance du nombre de variants en fonction de la moyenne de déviance postérieure (fichier d'entré = all.fit.txt)
genedir=paste0("DESMAN_",genename)
fichier_fit = figure_nb_variants(paste0(genedir,"/all_fit.txt"))

p <- ggplot(fichier_fit, aes(x = G, y = Dev)) + 
  geom_jitter(width = 0.1, height = 0.0)  + 
   theme_bw() + 
 
      theme(axis.text.x = element_text(angle=45, size=15, hjust = 1), 
       axis.text.y = element_text( size=15), 
       axis.title.x = element_text(size = 15),
       axis.title.y = element_text(size = 15))
p
ggsave(paste(genename,"_Optimal_variants.png"))

# dev.off()
```



## *Selection du nombre optimal de variants et du meilleur réplicat*

```{r function2,  eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy = FALSE}

##choisir le variant optimal à partir du graphe précédent : point de la tangente à la courbe

optimal_variant = 3


## Choix du meilleur réplicat du variant optimal
fichier_fit = figure_nb_variants(paste0(genedir,"/all_fit.txt"))

fichier_fit_opt = subset(fichier_fit, G == optimal_variant)
fichier_fit_opt$replicat = seq(1, nrow(fichier_fit_opt))

best_replicat = fichier_fit_opt$replicat[which.min(fichier_fit_opt$Dev)]
cat(paste0("Optimal_variant: ", optimal_variant, " & Best replicate: ",best_replicat, sep=" "))



## fonction 2 :lecture des haplotypes uniquement du meilleur réplicat
ALL_haplotypes <- function(fichier, optimal_variant, best_replicat) {
  fichier_haplotypes = read.csv(paste(fichier, optimal_variant, ".", best_replicat, "/Filtered_Tau_star_haplotypes", sep=''), sep='\t', header=FALSE)


  ## preparation du nom des colonnes
  col_names = c("gene", "position")
  for (j in (1:optimal_variant)){
    col_names = append(col_names, paste("variant", j, sep=""))
  }
  colnames(fichier_haplotypes) = col_names
  
  ### Ajout des colonnes : réplicat et index des positions variables
  fichier_haplotypes$replicat = best_replicat
  fichier_haplotypes$position_0 = seq(1, length(fichier_haplotypes[,1]))
  return(fichier_haplotypes)
}  



##Visualisation des différents haplotypes du meilleur réplicat

tableau_all_haplotypes = ALL_haplotypes(paste0(genedir,"/desman."), optimal_variant, best_replicat) 
melted_table <- select(tableau_all_haplotypes,position_0, 3:(3-1+optimal_variant), replicat)%>% gather(key = haplotype, value =letter, 2:(3-2+optimal_variant))

plot = ggplot(melted_table, aes(x=haplotype, y=position_0, fill=letter)) + 
  geom_tile() + 
    theme_light() + 
     xlab("Samples ") + 
      ylab("Positions") + 
       ggtitle("") + 
        theme(axis.text.x = element_text(angle=45, size=8, hjust = 1)) + 
          scale_fill_manual(values = wes_palette("Royal1", n = 4)) + 
            facet_grid( ~ replicat) 

plot
ggsave(paste(sep="_",genename,optimal_variant,"haplotypes.png"))

```


```{r function3, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy = FALSE}
# Fréquence des variants dans les échantillons

## Fonction 3 : pour lecture de la fréquence calculée des différents haplotypes (variants) par échantillon; fichier d'entré : Gamma_star.csv

lecture_frequences <- function(fichier, best_replicat, sep) {
   fichier_frequences = read.csv(fichier, sep=sep)
  nb_variants = length(fichier_frequences[1,])-1                                                                                                               ## nombre de variants = nombre de colonnes -1 
  col_names =c("sample")
  for (j in (1:nb_variants)){
     col_names = append(col_names, paste("variant", j, sep="_"))  
  }
  colnames(fichier_frequences) = col_names

fichier_frequences$replicat = as.character(best_replicat)
return (fichier_frequences)
}


## Lecture des fréquences calculées des différénts haplotypes (variants) pour le nombre de variant optimal et le meilleur réplicat
fichier_frequences_calculees = paste0(genedir,"/desman.")
fichier_frequences = lecture_frequences(paste(fichier_frequences_calculees, optimal_variant, ".", best_replicat,"/Gamma_star.csv", sep=''), best_replicat, ',') ## lecture frequences calculees

col_names =colnames(fichier_frequences)
fichier_frequence_gather = gather(fichier_frequences, key = "haplotype", value = "frequence", col_names[2]:col_names[1+optimal_variant])

```



## *Distribution des variants par Famille et Génération*
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE}

## Lire le fichier des métadata (informations sur les différents échantillons séquencés (noms des échantillons, familles, génération, age, sex...) et le joindre au fichier de fréquence gather
metadata=read.csv2("metadata_fugace.csv", sep='\t')
fichier_frequence_gather_metadata = full_join(fichier_frequence_gather, metadata, by=c("sample"="genoscope_sample_name"))


## Distribution des variants par famille et génération suivant l'age des animaux 

fichier_frequence_gather_metadata$Age = as.factor(fichier_frequence_gather_metadata$Age)

plot = ggplot(fichier_frequence_gather_metadata, aes(x=sample, y=frequence, color=haplotype,shape=Age))+ 
  geom_point() + 
    theme_light() +
      xlab("Samples ") + 
        ylab("Proportion (%)") + 
          ggtitle("") + 
            scale_color_brewer(palette="Paired") + 
              theme(axis.text.x = element_blank(), axis.text.y = element_text( size=15), axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15), legend.text = element_text( size=14), legend.title =  element_text( size=15)) + 
                labs(color = "Variant", shape="Age") + 
                  facet_grid(Gen ~ Fam) + scale_shape_manual(values=c(16,18))

plot
ggsave(paste(sep="_",genename,optimal_variant,"haplo_Gen_fam.png"))


```



## *Distribution des variants par condition d'élevage et Génération*
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy = FALSE}

plot = ggplot(fichier_frequence_gather_metadata, aes(x=sample, y=frequence, color=haplotype,shape=Age)) + 
        geom_point() + 
          theme_light() + 
            xlab("Samples ") +
             ylab("Proportion (%)") + 
              ggtitle("") + 
                scale_color_brewer(palette="Paired")+ theme(axis.text.x = element_blank(), axis.text.y = element_text( size=15), axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15), legend.text = element_text( size=14), legend.title =  element_text( size=15))+ labs(color = "Variant", shape="Age")+ facet_grid(Gen ~ Rearing) + scale_shape_manual(values=c(16,18))
ggplotly(plot)

ggsave(paste(sep="_",genename,optimal_variant,"haplo_Gen_Rearing.png"))

```
















